// ignore_for_file: non_constant_identifier_names

import 'graduation_project_model.dart';

final Category Tea_Herbal_Drinks = Category(
  categoryid: "C1",
  name: "Tea&Herbal Drinks",
  image: "assets/images/teaandherbaldrinks.png",
);
final Category HotCoffee = Category(
  categoryid: "C2",
  name: "Hot Coffee",
  image: "assets/images/hot coffee.png",
);
final Category IcedCoffee = Category(
  categoryid: "C3",
  name: "IcedCoffee",
  image: "assets/images/iced coffee category.png",
);
final Category Dessert_Snacks = Category(
  categoryid: "C4",
  name: "Dessert&Snacks",
  image: "assets/images/dessert and snacks logo.png",
);
final Category LightBites = Category(
  categoryid: "C5",
  name: "Light Bites",
  image: "assets/images/chicken panini logo.png",
);
final Category SoftDrinks = Category(
  categoryid: "C6",
  name: "Soft Drinks",
  image: "assets/images/soft drinks logo.png",
);
final Category FreshJuices = Category(
  categoryid: "C7",
  name: "Fresh Juices",
  image: "assets/images/fresh juice logo.png",
);
final Category Smoothies_Milkshakes = Category(
  categoryid: "C8",
  name: "Smoothies&\nMilkshakes",
  image: "assets/images/smoothie and shakes logo.png",
);

class Data {
  static List<Category> categosies = [
    Category(
      categoryid: "C1",
      name: "Tea&Herbal Drinks",
      image: "assets/images/teaandherbaldrinks.png",
    ),
    Category(
      categoryid: "C2",
      name: "Hot Coffee",
      image: "assets/images/hot coffee.png",
    ),
    Category(
      categoryid: "C3",
      name: "IcedCoffee",
      image: "assets/images/iced coffee category.png",
    ),
    Category(
      categoryid: "C4",
      name: "Dessert&Snacks",
      image: "assets/images/dessert and snacks logo.png",
    ),
    Category(
      categoryid: "C5",
      name: "Light Bites",
      image: "assets/images/chicken panini logo.png",
    ),
    Category(
      categoryid: "C6",
      name: "Soft Drinks",
      image: "assets/images/soft drinks logo.png",
    ),
    Category(
      categoryid: "C7",
      name: "Fresh Juices",
      image: "assets/images/fresh juice logo.png",
    ),
    Category(
      categoryid: "C8",
      name: "Smoothies&Milkshakes",
      image: "assets/images/smoothie and shakes logo.png",
    ),
  ];

  static List<Products> teaProducts = [
    Products(
      productid: "THD1",
      name: "Red Tea",
      price: 15.0,
      rate: 4.5,
      pretime: "5–7 min",
      image: "assets/images/redtea.png",
      category: Tea_Herbal_Drinks,
      description: "Classic black tea with a rich aroma and strong flavor.",
    ),
    Products(
      productid: "THD2",
      name: "Green Tea",
      price: 20.0,
      rate: 4.3,
      pretime: "6–8 min",
      image: "assets/images/green tea.png",
      category: Tea_Herbal_Drinks,
      description: "Light and refreshing green tea.",
    ),
    Products(
      productid: "THD3",
      name: "Karak Tea",
      price: 25.0,
      rate: 4.8,
      pretime: "7–10 min",
      image: "assets/images/karak tea.png",
      category: Tea_Herbal_Drinks,
      description: "Strong spiced tea with milk and cardamom.",
    ),
    Products(
      productid: "THD4",
      name: "Mint Green Tea",
      price: 22.0,
      rate: 4.4,
      pretime: "6–8 min",
      image: "assets/images/mint green tea.png",
      category: Tea_Herbal_Drinks,
      description: "Green tea blended with fresh mint.",
    ),
    Products(
      productid: "THD5",
      name: "Chamomile Tea",
      price: 20.0,
      rate: 4.6,
      pretime: "5–7 min",
      image: "assets/images/chamomile tea.png",
      category: Tea_Herbal_Drinks,
      description: "Relaxing chamomile herbal tea.",
    ),
    Products(
      productid: "THD6",
      name: "Karkade",
      price: 18.0,
      rate: 4.2,
      pretime: "5–7 min",
      image: "assets/images/karkade.png",
      category: Tea_Herbal_Drinks,
      description: "Hibiscus tea with tangy flavor.",
    ),
    Products(
      productid: "THD7",
      name: "Anise",
      price: 18.0,
      rate: 4.1,
      pretime: "4–6 min",
      image: "assets/images/anise.png",
      category: Tea_Herbal_Drinks,
      description: "Warm anise herbal drink.",
    ),
    Products(
      productid: "THD8",
      name: "Cinnamon & Milk",
      price: 22.0,
      rate: 4.7,
      pretime: "6–9 min",
      image: "assets/images/cinnamon milk.png",
      category: Tea_Herbal_Drinks,
      description: "Creamy milk with cinnamon.",
    ),
    Products(
      productid: "THD9",
      name: "Mint Red Tea",
      price: 18.0,
      rate: 4.4,
      pretime: "5–7 min",
      image: "assets/images/Mint Tea.png",
      category: Tea_Herbal_Drinks,
      description: "Black tea with fresh mint.",
    ),
    Products(
      productid: "THD10",
      name: "Helba",
      price: 18.0,
      rate: 4.0,
      pretime: "5–7 min",
      image: "assets/images/helba.png",
      category: Tea_Herbal_Drinks,
      description: "Traditional fenugreek drink.",
    ),
  ];

  static List<Products> hotCoffee = [
    Products(
      productid: "HC1",
      name: 'Espresso',
      price: 35.0,
      rate: 4.6,
      pretime: "3–5 min",
      image: 'assets/images/Espresso Coffee.png',
      category: HotCoffee,
      description:
          'Strong concentrated coffee shot with rich flavor and crema on top.',
    ),
    Products(
      productid: "HC2",
      name: 'Double Espresso',
      price: 45.0,
      rate: 4.7,
      pretime: "4–6 min",
      image: 'assets/images/double espresso.png',
      category: HotCoffee,
      description:
          'Two shots of espresso for a stronger and bolder coffee experience.',
    ),
    Products(
      productid: "HC3",
      name: 'Americano',
      price: 40.0,
      rate: 4.5,
      pretime: "4–6 min",
      image: 'assets/images/Americano.png',
      category: HotCoffee,
      description:
          'Espresso diluted with hot water for a smooth and balanced taste.',
    ),
    Products(
      productid: "HC4",
      name: 'Turkish Coffee',
      price: 30.0,
      rate: 4.4,
      pretime: "5–7 min",
      image: 'assets/images/Turkish coffee.png',
      category: HotCoffee,
      description:
          'Finely ground coffee brewed traditionally with rich foam and strong flavor.',
    ),
    Products(
      productid: "HC5",
      name: 'French Coffee',
      price: 42.0,
      rate: 4.3,
      pretime: "4–6 min",
      image: 'assets/images/french coffee.png',
      category: HotCoffee,
      description:
          'Coffee blended with flavors like vanilla or hazelnut for a creamy taste.',
    ),
    Products(
      productid: "HC6",
      name: 'Cappuccino',
      price: 50.0,
      rate: 4.8,
      pretime: "5–8 min",
      image: 'assets/images/cappuccino.png',
      category: HotCoffee,
      description: 'Espresso with steamed milk and thick milk foam on top.',
    ),
    Products(
      productid: "HC7",
      name: 'Latte',
      price: 55.0,
      rate: 4.7,
      pretime: "6–9 min",
      image: 'assets/images/latte.png',
      category: HotCoffee,
      description:
          'Espresso mixed with a large amount of steamed milk and light foam.',
    ),
    Products(
      productid: "HC8",
      name: 'Mocha',
      price: 60.0,
      rate: 4.6,
      pretime: "6–9 min",
      image: 'assets/images/mocha.png',
      category: HotCoffee,
      description:
          'Espresso with chocolate syrup and steamed milk, topped with foam.',
    ),
    Products(
      productid: "HC9",
      name: 'Spanish Latte',
      price: 65.0,
      rate: 4.5,
      pretime: "7–10 min",
      image: 'assets/images/Spanish Latte.png',
      category: HotCoffee,
      description:
          'Latte made with sweetened condensed milk for a rich and sweet flavor.',
    ),
    Products(
      productid: "HC10",
      name: 'White Mocha',
      price: 65.0,
      rate: 4.5,
      pretime: "7–10 min",
      image: 'assets/images/White Mocha.png',
      category: HotCoffee,
      description:
          'Espresso with white chocolate and steamed milk for a creamy taste.',
    ),
  ];

  static List<Products> icedCoffee = [
    Products(
      productid: "IC1",
      name: 'Classic Ice Coffee',
      price: 40.0,
      rate: 4.5,
      pretime: "3–5 min",
      image: 'assets/images/Iced Coffee.png',
      category: IcedCoffee,
      description:
          'Freshly brewed coffee served over ice for a refreshing cold experience.',
    ),
    Products(
      productid: "IC2",
      name: 'Iced Americano',
      price: 45.0,
      rate: 4.6,
      pretime: "3–5 min",
      image: 'assets/images/Iced Americano.png',
      category: IcedCoffee,
      description:
          'Espresso mixed with cold water and ice for a smooth bold flavor.',
    ),
    Products(
      productid: "IC3",
      name: 'Iced Latte',
      price: 55.0,
      rate: 4.7,
      pretime: "4–6 min",
      image: 'assets/images/Iced Latte.png',
      category: IcedCoffee,
      description:
          'Espresso combined with cold milk and ice for a creamy chilled drink.',
    ),
    Products(
      productid: "IC4",
      name: 'Iced Cappuccino',
      price: 55.0,
      rate: 4.7,
      pretime: "4–6 min",
      image: 'assets/images/iced cappuccino.png',
      category: IcedCoffee,
      description:
          'Chilled espresso with cold milk and light foam served over ice.',
    ),
    Products(
      productid: "IC5",
      name: 'Iced Mocha',
      price: 60.0,
      rate: 4.6,
      pretime: "5–7 min",
      image: 'assets/images/Iced Mocha.png',
      category: IcedCoffee,
      description: 'Espresso blended with chocolate and cold milk over ice.',
    ),
    Products(
      productid: "IC6",
      name: 'Iced Spanish Latte',
      price: 65.0,
      rate: 4.5,
      pretime: "5–7 min",
      image: 'assets/images/Iced Spanish Latte.png',
      category: IcedCoffee,
      description:
          'Cold latte mixed with sweetened condensed milk for a rich sweet flavor.',
    ),
    Products(
      productid: "IC7",
      name: 'Iced Caramel Latte',
      price: 65.0,
      rate: 4.5,
      pretime: "5–7 min",
      image: 'assets/images/Iced Caramel Latte.png',
      category: IcedCoffee,
      description:
          'Iced latte flavored with caramel syrup for a smooth sweet taste.',
    ),
    Products(
      productid: "IC8",
      name: 'Iced Vanilla Latte',
      price: 65.0,
      rate: 4.5,
      pretime: "5–7 min",
      image: 'assets/images/iced vanilla latte.png',
      category: IcedCoffee,
      description: 'Cold latte infused with vanilla syrup and served over ice.',
    ),
    Products(
      productid: "IC9",
      name: 'Iced White Mocha',
      price: 70.0,
      rate: 4.6,
      pretime: "5–7 min",
      image: 'assets/images/White Iced Mocha.png',
      category: IcedCoffee,
      description:
          'Espresso with white chocolate and cold milk served over ice.',
    ),
    Products(
      productid: "IC10",
      name: 'Iced Hazelnut Latte',
      price: 65.0,
      rate: 4.5,
      pretime: "5–7 min",
      image: 'assets/images/Hazelnut Iced Coffee.png',
      category: IcedCoffee,
      description: 'Refreshing iced latte flavored with hazelnut syrup.',
    ),
  ];

  static List<Products> dessertSnack = [
    Products(
      productid: "DS1",
      name: 'Classic Waffle',
      price: 45.0,
      rate: 4.5,
      pretime: "5–7 min",
      image: 'assets/images/classic waffle.png',
      category: Dessert_Snacks,
      description: 'Freshly baked waffle served with your choice of toppings.',
    ),
    Products(
      productid: "DS2",
      name: 'Chocolate Waffle',
      price: 55.0,
      rate: 4.6,
      pretime: "5–7 min",
      image: 'assets/images/chocolate waffle.png',
      category: Dessert_Snacks,
      description: 'Crispy waffle topped with rich chocolate sauce.',
    ),
    Products(
      productid: "DS3",
      name: 'Nutella Waffle',
      price: 60.0,
      rate: 4.7,
      pretime: "5–7 min",
      image: 'assets/images/nutella waffle.png',
      category: Dessert_Snacks,
      description: 'Golden waffle covered with creamy Nutella spread.',
    ),
    Products(
      productid: "DS4",
      name: 'Lotus Waffle',
      price: 60.0,
      rate: 4.7,
      pretime: "5–7 min",
      image: 'assets/images/Lotus waffle.png',
      category: Dessert_Snacks,
      description: 'Waffle topped with Lotus biscuit spread and crumbs.',
    ),
    Products(
      productid: "DS5",
      name: 'White Chocolate Waffle',
      price: 60.0,
      rate: 4.6,
      pretime: "5–7 min",
      image: 'assets/images/White choc waffle.png',
      category: Dessert_Snacks,
      description: 'Crispy waffle drizzled with smooth white chocolate.',
    ),
    Products(
      productid: "DS6",
      name: 'Oreo Waffle',
      price: 65.0,
      rate: 4.6,
      pretime: "5–7 min",
      image: 'assets/images/Oreo Waffle.png',
      category: Dessert_Snacks,
      description: 'Delicious waffle topped with crushed Oreo and chocolate.',
    ),
    Products(
      productid: "DS7",
      name: 'Classic Pancakes',
      price: 45.0,
      rate: 4.5,
      pretime: "5–7 min",
      image: 'assets/images/classic pancakes.png',
      category: Dessert_Snacks,
      description: 'Soft fluffy pancakes served warm.',
    ),
    Products(
      productid: "DS8",
      name: 'Chocolate Pancakes',
      price: 55.0,
      rate: 4.6,
      pretime: "5–7 min",
      image: 'assets/images/Chocolate Pancakes.png',
      category: Dessert_Snacks,
      description: 'Fluffy pancakes topped with rich chocolate sauce.',
    ),
    Products(
      productid: "DS9",
      name: 'Nutella Pancakes',
      price: 60.0,
      rate: 4.7,
      pretime: "5–7 min",
      image: 'assets/images/Nutella Pancakes.png',
      category: Dessert_Snacks,
      description: 'Pancakes covered with creamy Nutella spread.',
    ),
    Products(
      productid: "DS10",
      name: 'Lotus Pancakes',
      price: 60.0,
      rate: 4.7,
      pretime: "5–7 min",
      image: 'assets/images/Lotus Pancakes.png',
      category: Dessert_Snacks,
      description: 'Pancakes topped with Lotus spread and biscuit crumbs.',
    ),
    Products(
      productid: "DS11",
      name: 'White Chocolate Pancakes',
      price: 60.0,
      rate: 4.6,
      pretime: "5–7 min",
      image: 'assets/images/white Chocolate Pancakes.png',
      category: Dessert_Snacks,
      description: 'Soft pancakes drizzled with white chocolate.',
    ),
    Products(
      productid: "DS12",
      name: 'Chocolate Molten Cake',
      price: 70.0,
      rate: 4.8,
      pretime: "7–10 min",
      image: 'assets/images/Molten Chocolate.png',
      category: Dessert_Snacks,
      description: 'Warm chocolate cake with a rich molten center.',
    ),
    Products(
      productid: "DS13",
      name: 'Lotus Molten Cake',
      price: 75.0,
      rate: 4.7,
      pretime: "7–10 min",
      image: 'assets/images/lotus molten cake.png',
      category: Dessert_Snacks,
      description: 'Molten cake filled with creamy Lotus spread.',
    ),
    Products(
      productid: "DS14",
      name: 'Cheese Cake',
      price: 70.0,
      rate: 4.8,
      pretime: "7–10 min",
      image: 'assets/images/cheese cake.png',
      category: Dessert_Snacks,
      description: 'Smooth and creamy classic cheesecake slice.',
    ),
    Products(
      productid: "DS15",
      name: 'Lotus Cheesecake',
      price: 75.0,
      rate: 4.7,
      pretime: "7–10 min",
      image: 'assets/images/lotus cheese cake.png',
      category: Dessert_Snacks,
      description: 'Cheesecake topped with Lotus biscuit spread.',
    ),
    Products(
      productid: "DS16",
      name: 'Chocolate Ice Cream',
      price: 35.0,
      rate: 4.5,
      pretime: "3–5 min",
      image: 'assets/images/Chocolate Ice Cream.png',
      category: Dessert_Snacks,
      description: 'Creamy chocolate ice cream scoop.',
    ),
    Products(
      productid: "DS17",
      name: 'Vanilla Ice Cream',
      price: 35.0,
      rate: 4.5,
      pretime: "3–5 min",
      image: 'assets/images/Vanilla Ice Cream.png',
      category: Dessert_Snacks,
      description: 'Classic smooth vanilla ice cream.',
    ),
    Products(
      productid: "DS18",
      name: 'Mango Ice Cream',
      price: 40.0,
      rate: 4.6,
      pretime: "3–5 min",
      image: 'assets/images/Mango Ice Cream.png',
      category: Dessert_Snacks,
      description: 'Refreshing mango flavored ice cream.',
    ),
    Products(
      productid: "DS19",
      name: 'Strawberry Ice Cream',
      price: 40.0,
      rate: 4.6,
      pretime: "3–5 min",
      image: 'assets/images/strawberry icecream.png',
      category: Dessert_Snacks,
      description: 'Sweet strawberry ice cream with fruity flavor.',
    ),
    Products(
      productid: "DS20",
      name: 'Blueberry Ice Cream',
      price: 40.0,
      rate: 4.6,
      pretime: "3–5 min",
      image: 'assets/images/Blueberry Ice Cream.png',
      category: Dessert_Snacks,
      description: 'Creamy ice cream blended with blueberry flavor.',
    ),
    Products(
      productid: "DS21",
      name: 'Donut',
      price: 25.0,
      rate: 4.5,
      pretime: "2–4 min",
      image: 'assets/images/donut.png',
      category: Dessert_Snacks,
      description: 'Soft sweet donut with sugar or glaze topping.',
    ),
    Products(
      productid: "DS22",
      name: 'Cinnamon Roll',
      price: 30.0,
      rate: 4.5,
      pretime: "3–5 min",
      image: 'assets/images/cinnamon roll.png',
      category: Dessert_Snacks,
      description: 'Warm cinnamon roll topped with sweet icing.',
    ),
    Products(
      productid: "DS23",
      name: 'Nacho Cheese',
      price: 45.0,
      rate: 4.5,
      pretime: "5–7 min",
      image: 'assets/images/nacho cheese.png',
      category: Dessert_Snacks,
      description: 'Crunchy nachos served with melted cheese dip.',
    ),
    Products(
      productid: "DS24",
      name: 'Chips',
      price: 20.0,
      rate: 4.4,
      pretime: "2–4 min",
      image: 'assets/images/chips.png',
      category: Dessert_Snacks,
      description: 'Crispy salted potato chips.',
    ),
    Products(
      productid: "DS25",
      name: 'French Fries',
      price: 35.0,
      rate: 4.5,
      pretime: "3–5 min",
      image: 'assets/images/french fries.png',
      category: Dessert_Snacks,
      description: 'Golden crispy french fries served hot.',
    ),
  ];

  static List<Products> lightBites = [
    Products(
      productid: "LB1",
      name: 'Chicken Panini',
      price: 75.0,
      rate: 4.6,
      pretime: "7–10 min",
      image: 'assets/images/Chicken  Panini.png',
      category: LightBites,
      description:
          'Grilled panini filled with seasoned chicken and melted cheese.',
    ),
    Products(
      productid: "LB2",
      name: 'Tuna Melt Sandwich',
      price: 70.0,
      rate: 4.5,
      pretime: "7–10 min",
      image: 'assets/images/tuna melt.png',
      category: LightBites,
      description: 'Toasted sandwich loaded with tuna and melted cheese.',
    ),
    Products(
      productid: "LB3",
      name: 'Turkey and Cheese Croissant',
      price: 80.0,
      rate: 4.6,
      pretime: "5–8 min",
      image: 'assets/images/turkey and cheese croissant.png',
      category: LightBites,
      description: 'Flaky croissant stuffed with turkey slices and cheese.',
    ),
    Products(
      productid: "LB4",
      name: 'Chicken Caesar Wrap',
      price: 75.0,
      rate: 4.7,
      pretime: "7–10 min",
      image: 'assets/images/chicken caesar wrap.png',
      category: LightBites,
      description:
          'Grilled chicken wrap with fresh lettuce and Caesar dressing.',
    ),
    Products(
      productid: "LB5",
      name: 'Club Sandwich',
      price: 85.0,
      rate: 4.7,
      pretime: "8–12 min",
      image: 'assets/images/Club Sandwich.png',
      category: LightBites,
      description:
          'Triple-layer sandwich with chicken, turkey, cheese, and veggies.',
    ),
    Products(
      productid: "LB6",
      name: 'Mini Chicken Quesadilla',
      price: 70.0,
      rate: 4.6,
      pretime: "7–10 min",
      image: 'assets/images/Mini Chicken Quesadilla.png',
      category: LightBites,
      description:
          'Grilled tortilla filled with seasoned chicken and melted cheese.',
    ),
    Products(
      productid: "LB7",
      name: 'Fries Basket',
      price: 40.0,
      rate: 4.5,
      pretime: "5–7 min",
      image: 'assets/images/fries basket.png',
      category: LightBites,
      description: 'Basket of crispy golden french fries.',
    ),
    Products(
      productid: "LB8",
      name: 'Mozzarella Sticks',
      price: 55.0,
      rate: 4.6,
      pretime: "5–8 min",
      image: 'assets/images/mozzarilla sticks.png',
      category: LightBites,
      description: 'Crispy fried mozzarella sticks served with dipping sauce.',
    ),
    Products(
      productid: "LB9",
      name: 'Chicken Nuggets',
      price: 50.0,
      rate: 4.5,
      pretime: "5–7 min",
      image: 'assets/images/chicken nuggets.png',
      category: LightBites,
      description: 'Crispy chicken nuggets served hot and fresh.',
    ),
    Products(
      productid: "LB10",
      name: 'Garlic Bread with Cheese',
      price: 45.0,
      rate: 4.6,
      pretime: "5–7 min",
      image: 'assets/images/garlic bread.png',
      category: LightBites,
      description: 'Toasted garlic bread topped with melted cheese.',
    ),
  ];

  static List<Products> softDrinks = [
    Products(
      productid: "SD1",
      name: 'Coca-Cola',
      price: 25.0,
      rate: 4.6,
      pretime: "1–2 min",
      image: 'assets/images/coca cola.png',
      category: SoftDrinks,
      description: 'Chilled classic Coca-Cola served refreshing and fizzy.',
    ),
    Products(
      productid: "SD2",
      name: 'Diet Coke',
      price: 25.0,
      rate: 4.5,
      pretime: "1–2 min",
      image: 'assets/images/diet cola.png',
      category: SoftDrinks,
      description: 'Zero sugar Diet Coke with the same great taste.',
    ),
    Products(
      productid: "SD3",
      name: 'Pepsi',
      price: 25.0,
      rate: 4.5,
      pretime: "1–2 min",
      image: 'assets/images/Pepsi.png',
      category: SoftDrinks,
      description: 'Cold and refreshing Pepsi with bold cola flavor.',
    ),
    Products(
      productid: "SD4",
      name: '7UP',
      price: 25.0,
      rate: 4.4,
      pretime: "1–2 min",
      image: 'assets/images/7-UP.png',
      category: SoftDrinks,
      description: 'Crisp lemon-lime flavored sparkling drink.',
    ),
    Products(
      productid: "SD5",
      name: 'Mirinda Orange',
      price: 25.0,
      rate: 4.4,
      pretime: "1–2 min",
      image: 'assets/images/mirinda.png',
      category: SoftDrinks,
      description: 'Sweet and fizzy orange flavored soft drink.',
    ),
    Products(
      productid: "SD6",
      name: 'Fanta',
      price: 25.0,
      rate: 4.5,
      pretime: "1–2 min",
      image: 'assets/images/Fanta Orange.png',
      category: SoftDrinks,
      description: 'Refreshing sparkling drink with fruity orange taste.',
    ),
    Products(
      productid: "SD7",
      name: 'Sprite',
      price: 25.0,
      rate: 4.5,
      pretime: "1–2 min",
      image: 'assets/images/sprite.png',
      category: SoftDrinks,
      description: 'Cool lemon-lime soda served ice cold.',
    ),
    Products(
      productid: "SD8",
      name: 'Schweppes',
      price: 30.0,
      rate: 4.4,
      pretime: "1–2 min",
      image: 'assets/images/SCHWEPPES.png',
      category: SoftDrinks,
      description: 'Sparkling Schweppes with a crisp and refreshing taste.',
    ),
    Products(
      productid: "SD9",
      name: 'Red Bull',
      price: 45.0,
      rate: 4.6,
      pretime: "1–2 min",
      image: 'assets/images/Red Bull.png',
      category: SoftDrinks,
      description: 'Energy drink that boosts focus and performance.',
    ),
    Products(
      productid: "SD10",
      name: 'Mineral Water',
      price: 15.0,
      rate: 4.3,
      pretime: "1 min",
      image: 'assets/images/water.png',
      category: SoftDrinks,
      description: 'Chilled bottled mineral water.',
    ),
  ];

  static List<Products> freshJuices = [
    Products(
      productid: "FJ1",
      name: 'Orange Juice',
      price: 35.0,
      rate: 4.6,
      pretime: "3–5 min",
      image: 'assets/images/water.png',
      category: FreshJuices,
      description: 'Freshly squeezed orange juice served chilled.',
    ),
    Products(
      productid: "FJ2",
      name: 'Mango Juice',
      price: 40.0,
      rate: 4.7,
      pretime: "3–5 min",
      image: 'assets/images/mango.png',
      category: FreshJuices,
      description: 'Sweet and refreshing mango juice made from ripe mangoes.',
    ),
    Products(
      productid: "FJ3",
      name: 'Strawberry Juice',
      price: 40.0,
      rate: 4.6,
      pretime: "3–5 min",
      image: 'assets/images/strawberry.png',
      category: FreshJuices,
      description: 'Fresh strawberry juice blended to perfection.',
    ),
    Products(
      productid: "FJ4",
      name: 'Guava Juice',
      price: 35.0,
      rate: 4.5,
      pretime: "3–5 min",
      image: 'assets/images/Guava.png',
      category: FreshJuices,
      description: 'Natural guava juice with a rich tropical flavor.',
    ),
    Products(
      productid: "FJ5",
      name: 'Watermelon Juice',
      price: 35.0,
      rate: 4.5,
      pretime: "3–5 min",
      image: 'assets/images/watermelon.png',
      category: FreshJuices,
      description: 'Cool and refreshing watermelon juice.',
    ),
    Products(
      productid: "FJ6",
      name: 'Pineapple Juice',
      price: 40.0,
      rate: 4.6,
      pretime: "3–5 min",
      image: 'assets/images/pineapple.png',
      category: FreshJuices,
      description: 'Fresh pineapple juice with a sweet and tangy taste.',
    ),
    Products(
      productid: "FJ7",
      name: 'Kiwi Juice',
      price: 45.0,
      rate: 4.6,
      pretime: "3–5 min",
      image: 'assets/images/kiwi.png',
      category: FreshJuices,
      description: 'Refreshing kiwi juice packed with natural flavor.',
    ),
    Products(
      productid: "FJ8",
      name: 'Lemon Mint Juice',
      price: 30.0,
      rate: 4.7,
      pretime: "3–5 min",
      image: 'assets/images/lemon ment.png',
      category: FreshJuices,
      description: 'Fresh lemon juice blended with mint for a cooling effect.',
    ),
    Products(
      productid: "FJ9",
      name: 'Pomegranate Juice',
      price: 45.0,
      rate: 4.7,
      pretime: "3–5 min",
      image: 'assets/images/Pomegranate.png',
      category: FreshJuices,
      description: 'Rich and healthy pomegranate juice full of antioxidants.',
    ),
    Products(
      productid: "FJ10",
      name: 'Mixed Fruit Juice',
      price: 50.0,
      rate: 4.8,
      pretime: "4–6 min",
      image: 'assets/images/cocktail.png',
      category: FreshJuices,
      description: 'A delicious blend of seasonal fresh fruits.',
    ),
  ];

  static List<Products> smoothiesMilkshakes = [
    Products(
      productid: "SM1",
      name: 'Strawberry Smoothie',
      price: 55.0,
      rate: 4.7,
      pretime: "4–6 min",
      image: 'assets/images/Strawberry Smoothie.png',
      category: Smoothies_Milkshakes,
      description:
          'Creamy strawberry smoothie blended with fresh milk and ice.',
    ),
    Products(
      productid: "SM2",
      name: 'Mango Smoothie',
      price: 55.0,
      rate: 4.7,
      pretime: "4–6 min",
      image: 'assets/images/mango smoothie.png',
      category: Smoothies_Milkshakes,
      description: 'Rich mango smoothie made from ripe mangoes.',
    ),
    Products(
      productid: "SM3",
      name: 'Banana Smoothie',
      price: 50.0,
      rate: 4.6,
      pretime: "4–6 min",
      image: 'assets/images/banana smoothie.png',
      category: Smoothies_Milkshakes,
      description: 'Smooth and creamy banana blended drink.',
    ),
    Products(
      productid: "SM4",
      name: 'Mixed Berry Smoothie',
      price: 60.0,
      rate: 4.8,
      pretime: "4–6 min",
      image: 'assets/images/mixed berry smoothie.png',
      category: Smoothies_Milkshakes,
      description:
          'A refreshing blend of strawberries, blueberries, and raspberries.',
    ),
    Products(
      productid: "SM5",
      name: 'Avocado Smoothie',
      price: 60.0,
      rate: 4.6,
      pretime: "4–6 min",
      image: 'assets/images/avocado smoothie.png',
      category: Smoothies_Milkshakes,
      description: 'Creamy avocado smoothie with a rich texture.',
    ),
    Products(
      productid: "SM6",
      name: 'Chocolate Milkshake',
      price: 60.0,
      rate: 4.8,
      pretime: "4–6 min",
      image: 'assets/images/choco milkshake.png',
      category: Smoothies_Milkshakes,
      description: 'Classic chocolate milkshake topped with whipped cream.',
    ),
    Products(
      productid: "SM7",
      name: 'Vanilla Milkshake',
      price: 55.0,
      rate: 4.6,
      pretime: "4–6 min",
      image: 'assets/images/Vanilla Milkshakes.png',
      category: Smoothies_Milkshakes,
      description: 'Smooth vanilla milkshake with a creamy finish.',
    ),
    Products(
      productid: "SM8",
      name: 'Strawberry Milkshake',
      price: 60.0,
      rate: 4.7,
      pretime: "4–6 min",
      image: 'assets/images/strawberry milkshake.png',
      category: Smoothies_Milkshakes,
      description: 'Sweet strawberry milkshake blended to perfection.',
    ),
    Products(
      productid: "SM9",
      name: 'Oreo Milkshake',
      price: 65.0,
      rate: 4.9,
      pretime: "4–6 min",
      image: 'assets/images/oreo milkshake.png',
      category: Smoothies_Milkshakes,
      description: 'Creamy milkshake blended with crushed Oreo cookies.',
    ),
    Products(
      productid: "SM10",
      name: 'Lotus Milkshake',
      price: 70.0,
      rate: 4.9,
      pretime: "4–6 min",
      image: 'assets/images/lotus milkshake.png',
      category: Smoothies_Milkshakes,
      description: 'Rich milkshake blended with Lotus biscuit spread.',
    ),
  ];

  static List<Products> allProducts = [
    ...teaProducts,
    ...hotCoffee,
    ...icedCoffee,
    ...dessertSnack,
    ...lightBites,
    ...softDrinks,
    ...freshJuices,
    ...smoothiesMilkshakes,
  ];

  static List<Products> popularProducts = [
    Products(
      productid: "THD4",
      name: "Mint Green Tea",
      price: 22.0,
      rate: 4.4,
      pretime: "6–8 min",
      image: "assets/images/mint green tea.png",
      category: Tea_Herbal_Drinks,
      description: "Green tea blended with fresh mint.",
    ),
    Products(
      productid: "SM4",
      name: 'Mixed Berry Smoothie',
      price: 60.0,
      rate: 4.8,
      pretime: "4–6 min",
      image: 'assets/images/mixed berry smoothie.png',
      category: Smoothies_Milkshakes,
      description:
          'A refreshing blend of strawberries, blueberries, and raspberries.',
    ),
    Products(
      productid: "FJ2",
      name: 'Mango Juice',
      price: 40.0,
      rate: 4.7,
      pretime: "3–5 min",
      image: 'assets/images/mango.png',
      category: FreshJuices,
      description: 'Sweet and refreshing mango juice made from ripe mangoes.',
    ),
    Products(
      productid: "SD7",
      name: 'Sprite',
      price: 25.0,
      rate: 4.5,
      pretime: "1–2 min",
      image: 'assets/images/sprite.png',
      category: SoftDrinks,
      description: 'Cool lemon-lime soda served ice cold.',
    ),
  ];
}
